version: '3'



services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    restart: always

    ports:
      - "389:389"
      - "636:636"
    environment:
      - TZ=Asia/Shanghai
      - LDAP_ORGANISATION=lwl
      - LDAP_DOMAIN=lwl.com
      - LDAP_ADMIN_PASSWORD=156354
    volumes:
      - ./data/ldapdb:/var/lib/ldap
      - ./data/LdapConfig:/etc/ldap/slapd.d

  ldap-admin:

    image: osixia/phpldapadmin:latest

    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # 这个是另一个容器的名字
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8081:80"
    restart: unless-stopped
