version: '3'



services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    restart: always
    hostname: ldap.kenger.top
    ports:
      - "389:389"
      - "636:636"
    environment:
      - TZ=Asia/Shanghai
      - LDAP_ORGANISATION=kenger
      - LDAP_DOMAIN=kenger.top
      - LDAP_ADMIN_PASSWORD=xxx
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_VERIFY_CLIENT=try
    volumes:
      - ./data/ldapdb:/var/lib/ldap
      - ./data/local/ldap:/usr/local/ldap 
      - ./data/LdapConfig:/etc/ldap/slapd.d
      - ./data/assets/certs:/container/service/slapd/assets/certs

  ldap-admin:

    image: osixia/phpldapadmin:latest

    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # 这个是另一个容器的名字
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8081:80"
    restart: unless-stopped
