version: '3'
  


services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    restart: always

    ports:
      - "389:389"
      - "636:636"
    environment:
      - TZ=Asia/Shanghai
      - LDAP_ORGANISATION=lwl
      - LDAP_DOMAIN=lwl.com
      - LDAP_ADMIN_PASSWORD=156354
    volumes:
      - ./data/ldapdb:/var/lib/ldap
      - ./data/LdapConfig:/etc/ldap/slapd.d

  ldap-admin:

    image: ldapaccountmanager/lam:stable

    container_name: phpldapadmin
    # environment:
    #   - LAM_SKIP_PRECONFIGURE=false
    ports:
      - "8082:80"
    volumes:
      - ./data/ldapAdminDb:/var/lib/ldap
    restart: unless-stopped