# docker-compose版本
version: '3.7'
# 服务列表
services:
    # clash后台服务
    clash:
        # 设置image
        image: dreamacro/clash
        # 停止了总是重启
#        restart: always
        volumes:
            # 将配置文件挂载到容器中
            - ./clash_config:/root/.config/clash
        container_name: clash
        network_mode: host
#        ports:
#            # 这些端口都在配置文件中配置过，容器外地址可随心情配置
#            - [容器外http代理端口]:[容器内http代理端口，默认7890]
#            - [容器外sock5代理端口]:[容器内sock5代理端口，默认7890]
#            - [容器外REST API端口]:[容器内REST API端口，默认9090]
    clash_web:
        image: haishanh/yacd
        restart: always
        depends_on:
            # 依赖于上面的clash服务，在clash启动后，web才启动
            - clash
        ports:
            - 50080:80
        container_name: clash_web