version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - './alist:/opt/alist/data'
            - '/mnt/alistPan:/mnt/alistPan'
            - '/home/kenger:/home/kenger'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist:main'