version: '3'
services:
  webdav:
    image: morrisjobke/webdav
    restart: always
    ports:
      - "8889:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: kenger
      PASSWORD: 156354
    volumes:
      - ./data:/var/webdav
