version: '3'
services:
  frpc:
    image: snowdreamtech/frpc
    volumes:
      - .config/frpc.ini:/etc/frp/frpc.ini
    container_name: frpc_lwl

    ports:
     - 51223:51223

  v2ray:
    container_name: v2ray_lwl
    image: v2fly/v2fly-core:v4.31.0
    volumes:
      - ./config/config.json:/etc/v2ray/config.json
    ports:
      - 51223:51223